### ISSUE TITLE
Dark Zurich在线测试

### ISSUE THREAD

**Issue by creater-zq** [ygjwd12345/BiMix#1]
您好！我提交预测结果到测评网站时，网站提示我, Sorry,failed to upload file.
我的目录结构如下。我提交的是test_pred.zip文件。

![2021-12-03_20-05](https://user-images.githubusercontent.com/59300179/144599964-c86738a8-030c-4170-a913-ecac474c2816.png)

**Comment by ygjwd12345** [comment]
我的结果已经在服务器上公开了，你可以比对一下。 两个label下面东西是一样的 confidence 都是1.不过我看你的confidence好像少了一个文件。

**Comment by creater-zq** [comment]
> 

好的，谢谢了，我看看。

**Comment by creater-zq** [comment]
> 我的结果已经在服务器上公开了，你可以比对一下。 两个label下面东西是一样的 confidence 都是1.不过我看你的confidence好像少了一个文件。
我看你的labelTrainIds里面文件名是GOPR0364_frame_000001.png，我的是GOPR0364_frame_000001_rgb_anon.png。我看官网说脚本按照{sequence}_frame_{frame:0>6}*.png格式搜索，以为后面的*是通配符，这里有影响吗？

**Comment by creater-zq** [comment]
> 我的结果已经在服务器上公开了，你可以比对一下。 两个label下面东西是一样的 confidence 都是1.不过我看你的confidence好像少了一个文件。


我看你的labelTrainIds里面文件名是GOPR0364_frame_000001.png，我的是GOPR0364_frame_000001_rgb_anon.png。我看官网说脚本按照{sequence}frame{frame:0>6}\*.png格式搜索，以为后面的\*是通配符，请问这里有影响吗？

**Comment by ygjwd12345** [comment]
我是把后面删掉了。讲道理应该不是这个名字的问题。

**Comment by creater-zq** [comment]
> 

网速问题吗？需要挂梯子吗？

**Comment by creater-zq** [comment]
> 我是把后面删掉了。讲道理应该不是这个名字的问题。

我再试试。谢谢了

**Comment by creater-zq** [comment]
> 我是把后面删掉了。讲道理应该不是这个名字的问题。

能加一下您的qq或者微信吗？

**Comment by ygjwd12345** [comment]
> 网速问题吗？需要挂梯子吗？

我是在国外弄得 这个不清楚

**Comment by creater-zq** [comment]
> > 网速问题吗？需要挂梯子吗？
> 
> 我是在国外弄得 这个不清楚

![d453e77d5f25cc516503047fd03c094](https://user-images.githubusercontent.com/59300179/144605339-ad15c5e5-99de-4b38-bb71-d25b7e54967e.jpg)
网站报这个错误，我换个网络试试。谢谢了

**Comment by ygjwd12345** [comment]
我也遇见过这个问题，这个服务器总是挂掉。这应该不是你文件的问题。

**Comment by creater-zq** [comment]
> 

好的，我也用我师兄的电脑试了，还是这个问题，有可能是服务器挂了，谢谢，我明天继续试试。非常感谢您的解答。

**Comment by creater-zq** [comment]
> 我也遇见过这个问题，这个服务器总是挂掉。这应该不是你文件的问题。

确实是这个问题，我现在已经提交成功了，非常感谢您的帮助！

**Comment by Urbenyy** [comment]
![image](https://github.com/ygjwd12345/BiMix/assets/96567010/b43dff15-ede0-4fe7-92c0-42b34787f6ca)
nin
您好，冒昧打扰您，我也遇到这个问题了，请问您当时是怎么解决的呢，等两天自己就好了吗

**Comment by ygjwd12345** [comment]
就是服务器不好， 没办法

**Comment by Urbenyy** [comment]
好的，我再等一两天看看，非常感谢
