### ISSUE TITLE
绘图工具

### ISSUE THREAD

**Issue by creater-zq** [ygjwd12345/BiMix#3]
您好！我看DANNet的网络结构图，放大了字体什么的就糊了。
我把你的放大之后，还是很清晰，请问你网络结构采用什么绘图工具绘制的？谢谢

**Comment by ygjwd12345** [comment]
pdf的就会清晰 jpg的就模糊跟绘图跟绘图工具无关。 我一般用[drawio](https://app.diagrams.net/ )这个画.
