### ISSUE TITLE
模型的选择

### ISSUE THREAD

**Issue by creater-zq** [ygjwd12345/BiMix#4]
* 大佬，您好，我跑了你的代码，采用`RefineNet`，`lightnet=enhance_net_nopool()`；
* 最后选择`RefineNet_mixbf/dannet48000.pth'`和`RefineNet_mixbf/dannet_light48000.pth'`在`Dark Zurich val`上进行验证；
* 验证结果如下：
 ```py
road:	88.18
sidewalk:	58.12
building:	74.97
wall:	34.62
fence:	33.81
pole:	23.25
light:	8.03
sign:	13.37
vegetation:	58.67
terrain:	23.5
sky:	77.15
person:	17.58
rider:	1.15
car:	42.31
truck:	0.0
bus:	0.0
train:	0.0
motocycle:	11.55
bicycle:	20.36
mIoU: 30.88
 ```
* 由于这个结果和您在论文中提到的不太一致，所以想问一下，您的论文中所用的`lightnet`是采用了`zeroDCE`的还是`DANNet`的，以及最终所用的`pth`是哪一个`i_iter`的？
* 谢谢~

**Comment by ygjwd12345** [comment]
1.我们 采用的是 zeroDCE。
2. 对于 val 我们会测所有iter的结果，主要的结果比较是在test进行的。

**Comment by creater-zq** [comment]
> 1.我们 采用的是 zeroDCE。 2. 对于 val 我们会测所有iter的结果，主要的结果比较是在test进行的。

好的，谢谢
