### ISSUE TITLE
夜间语义分割

### ISSUE THREAD

**Issue by BUAA-LKG** [ygjwd12345/BiMix#5]
请问现在做这个方向的多吗？或者说这个方向有意义吗？求大佬赐教。

我是一名研究生，准备做这个，可是导师说现在有超清光摄像机，夜间语义分割没意义，就，，很难受。
我该怎么说服导师呢

**Comment by ygjwd12345** [comment]
谢谢你对这个方向的关注，很抱歉你的导师这么认为。从正面来讲，不是说有专业的仪器可以测量就可以否定以照片为基础的预测。按这个逻辑深度预测也毫无意义，因为早就有激光雷达。用计算机视觉来做这个东西就是要一个硬件需求与泛用性。但我不建议你说服你的老师。你可以顺着他的思路说，可能夜间语义分割的应用前景较窄但是这个问题可以泛化为在不利条件下的分割问题（Adverse Conditions-ACDC dataset）。不做domain adaptation 做domain generalise。 
希望我的建议对你有所帮助。

**Comment by ygjwd12345** [comment]
当然了，我做这个纯粹是感觉比较新鲜做的人还比较少。估计这篇以后我也不会在做这个方向了。

**Comment by BUAA-LKG** [comment]
> 谢谢你对这个方向的关注，很抱歉你的导师这么认为。从正面来讲，不是说有专业的仪器可以测量就可以否定以照片为基础的预测。按这个逻辑深度预测也毫无意义，因为早就有激光雷达。用计算机视觉来做这个东西就是要一个硬件需求与泛用性。但我不建议你说服你的老师。你可以顺着他的思路说，可能夜间语义分割的应用前景较窄但是这个问题可以泛化为在不利条件下的分割问题（Adverse Conditions-ACDC dataset）。不做domain adaptation 做domain generalise。 希望我的建议对你有所帮助。

非常感谢你的回答，我目前在看关于无监督跨域的文章，也就是做GTA5->City的，后续也想继续跟进域泛化的文章。
不知道能否加个联系方式交流一下？我是北航BUAA的一名研究生。

**Comment by ygjwd12345** [comment]
我的邮箱是 yangguanglei@hit.edu.cn. 你可以把你的联系方式发我邮箱
