### ISSUE TITLE
请问能提供一下在ACDC 数据集上的性能吗？

### ISSUE THREAD

**Issue by ZXXu96** [ygjwd12345/BiMix#6]
https://acdc.vision.ee.ethz.ch/benchmarks#semanticSegmentation 或许在这个链接中的ACDC性能（47.79）是您这边的官方性能吗？ 谢谢！

**Comment by ygjwd12345** [comment]
你好 Multi-Mix Bi-Mix都我们的结果。我们现在的名字叫Multi-Mix 。

**Comment by ZXXu96** [comment]
谢谢您的回复！ 那么还想请问，现在Arxiv上传的论文是Bi-Mix对吧？ Multi-Mix的论文还没有对吗。谢谢

**Comment by ygjwd12345** [comment]
基本没啥变化，就是换了名字，再把分刷上

**Comment by ZXXu96** [comment]
非常感谢。
