### ISSUE TITLE
DarkZurich在线测试

### ISSUE THREAD

**Issue by RyanQR** [ygjwd12345/BiMix#7]
您好，我最近希望能够利用DarkZurich数据集进行网络测试。但是在网站提交后，都报错Missing prediction for ground truth file GOPR0364_frame_000001_gt_labelTrainIds.png这个问题。浏览网站之前的论坛，感觉应该是文件结构的问题，但我根据网站的描述也没有发现问题，请问您对于这个问题有什么看法吗？
我的文件结构：
test.zip
      |---confidence
      |---labelTrainIds(GOPR0364_frame_000001.png,......)
      |---labelTrainIds_invalid

**Comment by ygjwd12345** [comment]
你可以下载一下网站里空开的submission，看看区别

**Comment by RyanQR** [comment]
> 

好的，感谢

**Comment by cixiao2022** [comment]
> 

你好，请问你的这个问题最终解决了吗，我在提交过程中也总是出现这个问题。
