### ISSUE TITLE
代码中的几个疑问

### ISSUE THREAD

**Issue by JCongLang** [ygjwd12345/BiMix#8]
![微信截图_20230318201350](https://user-images.githubusercontent.com/108472371/226105434-487e59ae-f2a3-4457-bb9a-17f8e080ca9c.png)
![微信截图_20230318201414](https://user-images.githubusercontent.com/108472371/226105633-02dd2b7a-3b6f-4132-96b6-31ca7de88c4f.png)

您好，我有几个问题不懂，请教一下大佬。
1、train.py中的这段代码将flip设为0是不是相当于没进行任何操作。这样做的意义是什么？
2、设为1的话对结果有什么影响吗？
3、getWeakInverseTransformParameters这个函数有什么作用？（个人感觉这个是不是有点多此一举？）
谢谢

**Comment by ygjwd12345** [comment]
这是classmix代码里设置的https://github.com/WilhelmT/ClassMix/blob/aa852919cd963b42503f57b74f5ef3feccd29c52/trainSSL.py#L374

**Comment by JCongLang** [comment]
好的，非常感谢
