### ISSUE TITLE
zeroDCE

### ISSUE THREAD

**Issue by JCongLang** [ygjwd12345/BiMix#9]
您好，我又来打扰您啦，我看到您在原始的zeroDCE.py的基础上加了x=torch.clamp(x,-2.1179,2.6400)
![image](https://user-images.githubusercontent.com/108472371/227492060-9be7b1b6-ca30-488c-af00-0b3853868310.png)
![image](https://user-images.githubusercontent.com/108472371/227492309-85e3319b-193c-43a4-a96b-aef3d74333cf.png)
1.为什么要把x压缩到[-2.1179,2.6400]这个范围呢？
2.[-2.1179,2.6400]是怎么确定的呢？

**Comment by ygjwd12345** [comment]
这里我真不记得咋回事了 大概是防止x值过于极端。你也可以取了试试。这个范围应该是看了看x的上下界情况自己试出来的。

**Comment by JCongLang** [comment]
非常感谢您的回复，我试了下去掉了x=torch.clamp(x,-2.1179,2.6400)，计算得到的loss是non。

**Comment by JCongLang** [comment]
您好，请问大佬您有用PSPNet作为语义分割网络进行训练和测试吗？因为我看到在DANNet里他最好的结果是用PSPNet得到的。

**Comment by ygjwd12345** [comment]
没有，不过当前的框架可以用PSPNet。

**Comment by JCongLang** [comment]
您好，在eva_ep.py中光照网络的选择是不是要用53行的lightnet =enhance_net_nopool()
![image](https://user-images.githubusercontent.com/108472371/229451677-65643b7a-9804-4cf9-a5c8-178a5c2d91fe.png)

**Comment by ygjwd12345** [comment]
应当是保持一致的

**Comment by JCongLang** [comment]
> 应当是保持一致的

我训练的时候用的enhance_net_nopool()，测试的时候没注意修改用的LightNet()，结果它参数能正常加载，得到的mIou还很高，我很疑惑。
